name: temp_scan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15 
  camera: ^0.11.0
  pdf: ^3.10.7
  pdfx: ^2.6.0
  open_filex: ^4.4.0
  share_plus: ^7.2.1
  flutter_launcher_icons: ^0.13.1
  image: ^4.1.3
  file_picker: ^8.0.0
  permission_handler: ^11.3.0
  image_picker: ^1.0.4

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  android: true
  ios: false

  color: "#0F0F0F"   # dark modern background

  image: assets/icon/icon.png

  android_12:
    color: "#0F0F0F"
    image: assets/icon/icon.png


flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/icon/icon.png"

